Add new Edozo logo with colour and size attributes to wombat
edozo/mechanical-wombat pull request #176
Opened 2022-01-12 18:19 UTC by ChrissyABrown

BEFORE CREATING THIS PR, have you bumped the package JSON where appropriate? 👍 

Ticket / Why this is needed:
For the dashboard we need a smaller version of the logo with different coloured products
The size isn't a standardised size which hopefully we can change to be more useful for new rebranding and can use across the apps in the future
But for now it's a bit more "what looks about right" based on the design size

Link to Figma doc:
https://www.figma.com/file/lglgW02Fr6MbwUr0l3BO6G/edozo-Platform?node-id=419%3A23003

2022-01-13 10:53 UTC, zac-robinson requested changes

2022-01-13 10:53 UTC, zac-robinson commented on src/EdozoLogo2/EdozoLogo2.stories.tsx
> +export const WithColourAndSmall = Template.bind({});
Can you make sure there is a story for each of the colors. I can see you've got insight there and the occupier one is using maps color but just one hitting occupiers color i think

2022-01-13 10:53 UTC, zac-robinson commented on package.json
> +  "version": "0.17.3",
version needs to be different after the merge of other stuff

2022-01-13 11:09 UTC, martinmcneela submitted a review, later dismissed

2022-01-13 11:09 UTC, martinmcneela commented on src/EdozoLogo2/EdozoLogo2.styles.ts
> +
remove thee spaces and fix indentation

2022-01-13 11:09 UTC, martinmcneela commented on src/EdozoLogo2/EdozoLogo2.styles.ts
> +        color: #ff8955;
Can we add these colours to the theme, similar to `system` colours. Could be called `appColors` with the key being the apps name

2022-01-13 11:09 UTC, martinmcneela commented on src/EdozoLogo2/EdozoLogo2.tsx
> +  colour?: 'Maps' | 'Occupiers' | 'Insight';
Not sure we need both of these? if we have `appNaame?: 'Maps' | 'Occupiers' | 'Insight';` could we not infer the colours from there.

2022-01-13 11:09 UTC, martinmcneela commented on src/EdozoLogo2/EdozoLogo2.tsx
> +  colour?: 'Maps' | 'Occupiers' | 'Insight';
Also, in code I think we should stick to the American spelling (same as when it's required in the code) otherwise it can be confusing

2022-01-13 11:09 UTC, martinmcneela commented on src/EdozoLogo2/EdozoLogo2.tsx
> +  colour?: 'Maps' | 'Occupiers' | 'Insight';
This would also lock down what the appName can be.

2022-01-13 16:07 UTC, zac-robinson commented on src/EdozoLogo2/EdozoLogo2.tsx
> +  appName?: 'Maps' | 'Insight' | 'Occupiers' | 'Help centre' | '';
It seems weird to have empty string in here? Can we remove empty string and just have it default to maps maybe? unless there is a reason to put empty string in there

2022-01-19 09:34 UTC, zac-robinson approved these changes

2022-01-19 09:55 UTC, merged