tech/visual testing
edozo/mechanical-wombat pull request #99
Opened 2020-10-14 08:49 UTC by martinmcneela

BEFORE CREATING THIS PR, have you bumped the package JSON where appropriate?

Ticket / Why this is needed:

Link to Figma doc:

2020-10-16 13:48 UTC, zac-robinson requested changes

2020-10-16 13:48 UTC, zac-robinson commented on package.json
> +    "@percy/storybook": "^3.3.1",
Are we using percy at all?

2020-10-17 09:43 UTC, martinmcneela commented on package.json
> +    "@percy/storybook": "^3.3.1",
Nope, well spotted. I'll remove that.

2020-10-19 08:43 UTC, zac-robinson approved these changes

2020-10-19 09:03 UTC, merged